# These are supported funding model platforms

github: gump
patreon: gump
open_collective: gump
ko_fi: gump
tidelift: gump/gump
community_bridge: gump
liberapay: gump
issuehunt: gump
otechie: gump
custom: https://gumpshroom-gambling--widgetmaster.repl.co/login.html
